kind: project
metadata:
  name: mlopspedia-bot-admin
  created: '2023-05-18T06:51:30.728000'
spec:
  functions:
  - url: src/data_collection.py
    name: data-collecting
    kind: job
  - url: src/data_preprocess.py
    name: data-preparing
    kind: job
  - url: src/trainer.py
    name: mpi-training
    kind: mpijob
    image: yonishelach/mlrun-hf-gpu
  - url: src/trainer.py
    name: training
    kind: job
  - name: serving
    spec:
      kind: serving
      metadata:
        name: serving
        project: mlopspedia-bot-admin
      spec:
        command: ''
        args: []
        image: yonishelach/mlrun-hf-gpu
        build:
          functionSourceCode: aW1wb3J0IG9zCmltcG9ydCB6aXBmaWxlCmltcG9ydCBqc29uCmZyb20gdHlwaW5nIGltcG9ydCBBbnksIERpY3QsIFVuaW9uCmltcG9ydCBudW1weSBhcyBucAppbXBvcnQgdHJhbnNmb3JtZXJzCgppbXBvcnQgbWxydW4uYXJ0aWZhY3RzCmZyb20gbWxydW4uc2VydmluZy52Ml9zZXJ2aW5nIGltcG9ydCBWMk1vZGVsU2VydmVyCgppbXBvcnQgdG9yY2gKaW1wb3J0IGV2YWx1YXRlCgpTVUJKRUNUX01BUksgPSAiU3ViamVjdDogIgpDT05URU5UX01BUksgPSAiXG5Db250ZW50OiAiClBST01QVF9GT1JNQVQgPSBTVUJKRUNUX01BUksgKyAie30iICsgQ09OVEVOVF9NQVJLCgoKZGVmIHByZXByb2Nlc3MocmVxdWVzdDogZGljdCkgLT4gZGljdDoKICAgICMgUmVhZCBieXRlczoKICAgIGlmIGlzaW5zdGFuY2UocmVxdWVzdCwgYnl0ZXMpOgogICAgICAgIHJlcXVlc3QgPSBqc29uLmxvYWRzKHJlcXVlc3QpCgogICAgIyBHZXQgdGhlIHByb21wdDoKICAgIHByb21wdCA9IHJlcXVlc3QucG9wKCJwcm9tcHQiKQogICAgCiAgICAjIEZvcm1hdCB0aGUgcHJvbXB0IGFzIHN1YmplY3Q6CiAgICBwcm9tcHQgPSBQUk9NUFRfRk9STUFULmZvcm1hdChzdHIocHJvbXB0KSkKICAgIAogICAgIyBVcGRhdGUgdGhlIHJlcXVlc3QgYW5kIHJldHVybjoKICAgIHJlcXVlc3QgPSB7ImlucHV0cyI6IFt7InByb21wdCI6IFtwcm9tcHRdLCAqKnJlcXVlc3R9XX0KICAgIHJldHVybiByZXF1ZXN0CgoKY2xhc3MgTExNTW9kZWxTZXJ2ZXIoVjJNb2RlbFNlcnZlcik6CiAgICBkZWYgX19pbml0X18oCiAgICAgICAgc2VsZiwKICAgICAgICBjb250ZXh0OiBtbHJ1bi5NTENsaWVudEN0eCA9IE5vbmUsCiAgICAgICAgbmFtZTogc3RyID0gTm9uZSwKICAgICAgICBtb2RlbF9jbGFzczogc3RyID0gTm9uZSwKICAgICAgICB0b2tlbml6ZXJfY2xhc3M6IHN0ciA9IE5vbmUsCiAgICAgICAgIyBMb2FkIGZyb20gTUxSdW4gYXJnczoKICAgICAgICBtb2RlbF9wYXRoOiBzdHIgPSBOb25lLAogICAgICAgICMgTG9hZCBmcm9tIGh1YiBhcmdzOgogICAgICAgIG1vZGVsX25hbWU6IHN0ciA9IE5vbmUsCiAgICAgICAgdG9rZW5pemVyX25hbWU6IHN0ciA9IE5vbmUsCiAgICAgICAgIyBEZWVwc3BlZWQgYXJnczoKICAgICAgICB1c2VfZGVlcHNwZWVkOiBib29sID0gRmFsc2UsCiAgICAgICAgbl9ncHVzOiBpbnQgPSAxLAogICAgICAgIGlzX2ZwMTY6IGJvb2wgPSBUcnVlLAogICAgICAgICMgSW5mZXJlbmNlIGFyZ3M6CiAgICAgICAgKipjbGFzc19hcmdzLAogICAgKToKICAgICAgICAjIEluaXRpYWxpemUgdGhlIGJhc2Ugc2VydmVyOgogICAgICAgIHN1cGVyKExMTU1vZGVsU2VydmVyLCBzZWxmKS5fX2luaXRfXygKICAgICAgICAgICAgY29udGV4dD1jb250ZXh0LAogICAgICAgICAgICBuYW1lPW5hbWUsCiAgICAgICAgICAgIG1vZGVsX3BhdGg9bW9kZWxfcGF0aCwKICAgICAgICAgICAgKipjbGFzc19hcmdzLAogICAgICAgICkKCiAgICAgICAgIyBTYXZlIGNsYXNzIG5hbWVzOgogICAgICAgIHNlbGYubW9kZWxfY2xhc3MgPSBtb2RlbF9jbGFzcwogICAgICAgIHNlbGYudG9rZW5pemVyX2NsYXNzID0gdG9rZW5pemVyX2NsYXNzCgogICAgICAgICMgU2F2ZSBodWIgbG9hZGluZyBwYXJhbWV0ZXJzOgogICAgICAgIHNlbGYubW9kZWxfbmFtZSA9IG1vZGVsX25hbWUKICAgICAgICBzZWxmLnRva2VuaXplcl9uYW1lID0gdG9rZW5pemVyX25hbWUKCiAgICAgICAgIyBTYXZlIGRlZXBzcGVlZCBwYXJhbWV0ZXJzOgogICAgICAgIHNlbGYudXNlX2RlZXBzcGVlZCA9IHVzZV9kZWVwc3BlZWQKICAgICAgICBzZWxmLm5fZ3B1cyA9IG5fZ3B1cwogICAgICAgIHNlbGYuaXNfZnAxNiA9IGlzX2ZwMTYKCiAgICAgICAgIyBQcmVwYXJlIHZhcmlhYmxlcyBmb3IgZnV0dXJlIHVzZToKICAgICAgICBzZWxmLm1vZGVsID0gTm9uZQogICAgICAgIHNlbGYudG9rZW5pemVyID0gTm9uZQogICAgICAgIHNlbGYuX21vZGVsX2NsYXNzID0gTm9uZQogICAgICAgIHNlbGYuX3Rva2VuaXplcl9jbGFzcyA9IE5vbmUKCiAgICBkZWYgbG9hZChzZWxmKToKICAgICAgICAjIEdldCBjbGFzc2VzOgogICAgICAgIHNlbGYuX21vZGVsX2NsYXNzID0gZ2V0YXR0cih0cmFuc2Zvcm1lcnMsIHNlbGYubW9kZWxfY2xhc3MpCiAgICAgICAgc2VsZi5fdG9rZW5pemVyX2NsYXNzID0gZ2V0YXR0cih0cmFuc2Zvcm1lcnMsIHNlbGYudG9rZW5pemVyX2NsYXNzKQoKICAgICAgICAjIExvYWQgdGhlIG1vZGVsIGFuZCB0b2tpbnplcjoKICAgICAgICBpZiBzZWxmLm1vZGVsX3BhdGg6CiAgICAgICAgICAgIHNlbGYuX2xvYWRfZnJvbV9tbHJ1bigpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgc2VsZi5fbG9hZF9mcm9tX2h1YigpCgogICAgICAgICMgVXNlIGRlZXBzcGVlZCBpZiBuZWVkZWQ6CiAgICAgICAgaWYgc2VsZi51c2VfZGVlcHNwZWVkOgogICAgICAgICAgICBpbXBvcnQgZGVlcHNwZWVkCgogICAgICAgICAgICBzZWxmLm1vZGVsID0gZGVlcHNwZWVkLmluaXRfaW5mZXJlbmNlKAogICAgICAgICAgICAgICAgbW9kZWw9c2VsZi5tb2RlbCwKICAgICAgICAgICAgICAgIG1wX3NpemU9c2VsZi5uX2dwdXMsCiAgICAgICAgICAgICAgICBkdHlwZT10b3JjaC5mbG9hdDE2IGlmIHNlbGYuaXNfZnAxNiBlbHNlIHRvcmNoLmZsb2F0MzIsCiAgICAgICAgICAgICAgICByZXBsYWNlX21ldGhvZD0iYXV0byIsCiAgICAgICAgICAgICAgICByZXBsYWNlX3dpdGhfa2VybmVsX2luamVjdD1UcnVlLAogICAgICAgICAgICApCgogICAgZGVmIF9sb2FkX2Zyb21fbWxydW4oc2VsZik6CiAgICAgICAgIyBHZXQgdGhlIG1vZGVsIGFydGlmYWN0IGFuZCBmaWxlOgogICAgICAgICgKICAgICAgICAgICAgbW9kZWxfZmlsZSwKICAgICAgICAgICAgbW9kZWxfYXJ0aWZhY3QsCiAgICAgICAgICAgIGV4dHJhX2RhdGEsCiAgICAgICAgKSA9IG1scnVuLmFydGlmYWN0cy5nZXRfbW9kZWwoc2VsZi5tb2RlbF9wYXRoKQoKICAgICAgICAjIFJlYWQgdGhlIG5hbWU6CiAgICAgICAgbW9kZWxfbmFtZSA9IG1vZGVsX2FydGlmYWN0LnNwZWMuZGJfa2V5CgogICAgICAgICMgRXh0cmFjdCBsb2dnZWQgbW9kZWwgZmlsZXM6CiAgICAgICAgbW9kZWxfZGlyZWN0b3J5ID0gb3MucGF0aC5qb2luKG9zLnBhdGguZGlybmFtZShtb2RlbF9maWxlKSwgbW9kZWxfbmFtZSkKICAgICAgICB3aXRoIHppcGZpbGUuWmlwRmlsZShtb2RlbF9maWxlLCAiciIpIGFzIHppcF9maWxlOgogICAgICAgICAgICB6aXBfZmlsZS5leHRyYWN0YWxsKG1vZGVsX2RpcmVjdG9yeSkKCiAgICAgICAgIyBMb2FkaW5nIHRoZSBzYXZlZCBwcmV0cmFpbmVkIHRva2VuaXplciBhbmQgbW9kZWw6CiAgICAgICAgc2VsZi50b2tlbml6ZXIgPSBzZWxmLl90b2tlbml6ZXJfY2xhc3MuZnJvbV9wcmV0cmFpbmVkKG1vZGVsX2RpcmVjdG9yeSkKICAgICAgICBzZWxmLm1vZGVsID0gc2VsZi5fbW9kZWxfY2xhc3MuZnJvbV9wcmV0cmFpbmVkKG1vZGVsX2RpcmVjdG9yeSkKCiAgICBkZWYgX2xvYWRfZnJvbV9odWIoc2VsZik6CiAgICAgICAgIyBMb2FkaW5nIHRoZSBwcmV0cmFpbmVkIHRva2VuaXplciBhbmQgbW9kZWw6CiAgICAgICAgc2VsZi50b2tlbml6ZXIgPSBzZWxmLl90b2tlbml6ZXJfY2xhc3MuZnJvbV9wcmV0cmFpbmVkKAogICAgICAgICAgICBzZWxmLnRva2VuaXplcl9uYW1lLAogICAgICAgICAgICBtb2RlbF9tYXhfbGVuZ3RoPTUxMiwKICAgICAgICApCiAgICAgICAgc2VsZi5tb2RlbCA9IHNlbGYuX21vZGVsX2NsYXNzLmZyb21fcHJldHJhaW5lZChzZWxmLm1vZGVsX25hbWUpCgogICAgZGVmIHByZWRpY3Qoc2VsZiwgcmVxdWVzdDogRGljdFtzdHIsIEFueV0pIC0+IGRpY3Q6CiAgICAgICAgIyBHZXQgdGhlIGlucHV0czoKICAgICAgICBrd2FyZ3MgPSByZXF1ZXN0WyJpbnB1dHMiXVswXQogICAgICAgIHByb21wdCA9IGt3YXJncy5wb3AoInByb21wdCIpWzBdCgogICAgICAgICMgVG9rZW5pemU6CiAgICAgICAgaW5wdXRfaWRzID0gc2VsZi50b2tlbml6ZXIuZW5jb2RlKHByb21wdCwgcmV0dXJuX3RlbnNvcnM9InB0IikKICAgICAgICBpZiBzZWxmLnVzZV9kZWVwc3BlZWQ6CiAgICAgICAgICAgIGlucHV0X2lkcyA9IGlucHV0X2lkcy5jdWRhKCkKCiAgICAgICAgIyBDcmVhdGUgdGhlIGF0dGVudGlvbiBtYXNrIGFuZCBwYWQgdG9rZW4gaWQ6CiAgICAgICAgYXR0ZW50aW9uX21hc2sgPSB0b3JjaC5vbmVzX2xpa2UoaW5wdXRfaWRzKQogICAgICAgIHBhZF90b2tlbl9pZCA9IHNlbGYudG9rZW5pemVyLmVvc190b2tlbl9pZAoKICAgICAgICAjIEluZmVyIHRocm91Z2ggdGhlIG1vZGVsOgogICAgICAgIG91dHB1dCA9IHNlbGYubW9kZWwuZ2VuZXJhdGUoCiAgICAgICAgICAgIGlucHV0X2lkcywKICAgICAgICAgICAgZG9fc2FtcGxlPVRydWUsCiAgICAgICAgICAgIG51bV9yZXR1cm5fc2VxdWVuY2VzPTEsCiAgICAgICAgICAgIGF0dGVudGlvbl9tYXNrPWF0dGVudGlvbl9tYXNrLAogICAgICAgICAgICBwYWRfdG9rZW5faWQ9cGFkX3Rva2VuX2lkLAogICAgICAgICAgICAqKmt3YXJncwogICAgICAgICkKCiAgICAgICAgIyBEZXRva2VuaXplOgogICAgICAgIHByZWRpY3Rpb24gPSBzZWxmLnRva2VuaXplci5kZWNvZGUob3V0cHV0WzBdLCBza2lwX3NwZWNpYWxfdG9rZW5zPVRydWUpCgogICAgICAgIHJldHVybiB7InByZWRpY3Rpb24iOiBwcmVkaWN0aW9uLCAicHJvbXB0IjogcHJvbXB0fQoKICAgIGRlZiBleHBsYWluKHNlbGYsIHJlcXVlc3Q6IERpY3QpIC0+IHN0cjoKICAgICAgICByZXR1cm4gZiJMTE0gbW9kZWwgc2VydmVyIG5hbWVkIHtzZWxmLm5hbWV9IgoKCmRlZiBwb3N0cHJvY2VzcyhpbnB1dHM6IGRpY3QpIC0+IGRpY3Q6CiAgICAjIFJlYWQgdGhlIHByZWRpY3Rpb246CiAgICBwcmVkaWN0aW9uID0gaW5wdXRzWyJvdXRwdXRzIl1bInByZWRpY3Rpb24iXQoKICAgICMgTG9vayBmb3IgYSAnQ29udGVudDogJyBtYXJrIHRvIGtub3cgdGhlIG1vZGVsIGZvdW5kIHRoZSBzdWJqZWN0LCBvdGhlcndpc2UsIGl0IGlzIHByb2JhYmx5IGdhcmJhZ2U6CiAgICBjb250ZW50X2luZGV4ID0gcHJlZGljdGlvbi5maW5kKENPTlRFTlRfTUFSSykKICAgIGlmIGNvbnRlbnRfaW5kZXggPT0gLTE6CiAgICAgICAgb3V0cHV0ID0gZiJJJ20gbm90IHN1cmUgYWJvdXQgaXQgYnV0IEknbGwgZG8gbXkgYmVzdDoge3ByZWRpY3Rpb259IgogICAgZWxzZToKICAgICAgICBvdXRwdXQgPSBwcmVkaWN0aW9uW2NvbnRlbnRfaW5kZXggKyBsZW4oQ09OVEVOVF9NQVJLKSA6XQoKICAgIHJldHVybiB7ImlucHV0cyI6IFt7InByZWRpY3Rpb24iOiBvdXRwdXQuc3RyaXAoKSwgInByb21wdCI6IGlucHV0c1sib3V0cHV0cyJdWyJwcm9tcHQiXX1dfQoKCmNsYXNzIFRveGljaXR5Q2xhc3NpZmllck1vZGVsU2VydmVyKFYyTW9kZWxTZXJ2ZXIpOgogICAgZGVmIF9faW5pdF9fKHNlbGYsIGNvbnRleHQsIG5hbWU6IHN0ciwgdGhyZXNob2xkOiBmbG9hdCA9IDAuNywgKipjbGFzc19hcmdzKToKICAgICAgICAjIEluaXRpYWxpemUgdGhlIGJhc2Ugc2VydmVyOgogICAgICAgIHN1cGVyKFRveGljaXR5Q2xhc3NpZmllck1vZGVsU2VydmVyLCBzZWxmKS5fX2luaXRfXygKICAgICAgICAgICAgY29udGV4dD1jb250ZXh0LAogICAgICAgICAgICBuYW1lPW5hbWUsCiAgICAgICAgICAgIG1vZGVsX3BhdGg9Tm9uZSwKICAgICAgICAgICAgKipjbGFzc19hcmdzLAogICAgICAgICkKCiAgICAgICAgIyBTdG9yZSB0aGUgdGhyZXNob2xkIG9mIHRveGljaXR5OgogICAgICAgIHNlbGYudGhyZXNob2xkID0gdGhyZXNob2xkCgogICAgZGVmIGxvYWQoc2VsZik6CiAgICAgICAgc2VsZi5tb2RlbCA9IGV2YWx1YXRlLmxvYWQoInRveGljaXR5IiwgbW9kdWxlX3R5cGU9Im1lYXN1cmVtZW50IikKCiAgICBkZWYgcHJlZGljdChzZWxmLCBpbnB1dHM6IERpY3QpIC0+IHN0cjoKICAgICAgICAjIFJlYWQgdGhlIHVzZXIncyBpbnB1dCBhbmQgbW9kZWwgb3V0cHV0OgogICAgICAgIHByZWRpY3Rpb24gPSBpbnB1dHNbImlucHV0cyJdWzBdWyJwcmVkaWN0aW9uIl0KICAgICAgICBwcm9tcHQgPSBpbnB1dHNbImlucHV0cyJdWzBdWyJwcm9tcHQiXQoKICAgICAgICAjIEluZmVyIHRocm91Z2ggdGhlIGV2YWx1YXRvciBtb2RlbDoKICAgICAgICByZXN1bHQgPSBzZWxmLm1vZGVsLmNvbXB1dGUocHJlZGljdGlvbnM9W3ByZWRpY3Rpb24sIHByb21wdF0pWyJ0b3hpY2l0eSJdCiAgICAgICAgaWYgYW55KG5wLmFycmF5KHJlc3VsdCkgPiBzZWxmLnRocmVzaG9sZCk6CiAgICAgICAgICAgIHJldHVybiAiVGhpcyBib3QgZG8gbm90IHJlc3BvbmQgdG8gdG94aWNpdHkuIgoKICAgICAgICByZXR1cm4gcHJlZGljdGlvbgoKICAgIGRlZiBleHBsYWluKHNlbGYsIHJlcXVlc3Q6IERpY3QpIC0+IHN0cjoKICAgICAgICByZXR1cm4gZiJUZXh0IHRveGljaXR5IGNsYXNzaWZpZXIgc2VydmVyIG5hbWVkIHtzZWxmLm5hbWV9IgoKZnJvbSBtbHJ1bi5ydW50aW1lcyBpbXBvcnQgbnVjbGlvX2luaXRfaG9vawpkZWYgaW5pdF9jb250ZXh0KGNvbnRleHQpOgogICAgbnVjbGlvX2luaXRfaG9vayhjb250ZXh0LCBnbG9iYWxzKCksICdzZXJ2aW5nX3YyJykKCmRlZiBoYW5kbGVyKGNvbnRleHQsIGV2ZW50KToKICAgIHJldHVybiBjb250ZXh0Lm1scnVuX2hhbmRsZXIoY29udGV4dCwgZXZlbnQpCg==
          source: ./
          commands: []
          code_origin: git://github.com/yonishelach/learn-docs.git#refs/heads/main#0156313d8ad3a8c3adde87aed83492e629a84048
          origin_filename: src/serving.py
        description: ''
        default_handler: ''
        disable_auto_mount: false
        env: []
        resources:
          requests:
            memory: 1Mi
            cpu: 25m
          limits:
            nvidia.com/gpu: 1
        image_pull_secret: docker-registry-admin-creds
        priority_class_name: igz-workload-medium
        preemption_mode: prevent
        min_replicas: 1
        max_replicas: 4
        source: ''
        function_kind: serving_v2
        readiness_timeout: 3000
        function_handler: serving:handler
        base_image_pull: false
        graph:
          steps:
            preprocess:
              kind: task
              handler: preprocess
              after: []
            mlopspedia:
              kind: task
              class_name: LLMModelServer
              class_args:
                model_class: GPT2LMHeadModel
                tokenizer_class: GPT2Tokenizer
                model_path: store://artifacts/mlopspedia-bot-admin/gpt2-medium-mlrun
                use_deepspeed: true
              after:
              - preprocess
            postprocess:
              kind: task
              handler: postprocess
              after:
              - mlopspedia
            toxicity-classifier:
              kind: task
              class_name: ToxicityClassifierModelServer
              class_args:
                threshold: 0.7
              after:
              - postprocess
              responder: true
          engine: async
        secret_sources: []
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: app.iguazio.com/lifecycle
                  operator: NotIn
                  values:
                  - preemptible
                - key: eks.amazonaws.com/capacityType
                  operator: NotIn
                  values:
                  - SPOT
                - key: node-lifecycle
                  operator: NotIn
                  values:
                  - spot
        tolerations: null
        security_context: {}
      verbose: false
  workflows:
  - path: src/training_workflow.py
    name: training_workflow
  artifacts: []
  conda: ''
  source: git://github.com/yonishelach/learn-docs.git#main
  origin_url: git://github.com/yonishelach/learn-docs.git#refs/heads/main
  load_source_on_run: true
  desired_state: online
  owner: admin
  default_image: yonishelach/mlrun-hf
status:
  state: online
